name: Update README with latest blog post

on:
  schedule:
    # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install required packages
      run: npm install rss-parser

    - name: Create Node.js script to fetch latest blog post and count
      run: |
        echo "const fs = require('fs'); \
        const Parser = require('rss-parser'); \
        const parser = new Parser(); \
        const today = new Date().toISOString().slice(0, 10); \
        (async () => { \
          const feed = await parser.parseURL('https://amoses.dev/rss.xml'); \
          const postCount = feed.items.length; \
          const latestPost = feed.items[0]; \
          const postText = postCount === 1 ? 'post' : 'posts'; \
          const newReadmeContent = \`Welcome to my profile! I'm Andrew, a Computer Science student at the University of Wisconsin. You can learn more about me (and read some of my writing) at https://amoses.dev. There are \${postCount} blog \${postText}, and the latest one is titled [\${latestPost.title}](\${latestPost.link}). (This README is automatically updated -- last checked \${today}!)\`; \
          fs.writeFileSync('README.md', newReadmeContent); \
        })();" > updateReadme.js

    - name: Run the Node.js script
      run: node updateReadme.js

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.bot }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README with latest blog post"
        git push https://x-access-token:${GH_TOKEN}@github.com/AndrewDTR/AndrewDTR.git HEAD:main
